export const EDIT_ITEM_EXISTING = 'utter/editing/EDIT_ITEM_EXISTING'
export const EDIT_ITEM_NEW = 'utter/editing/EDIT_ITEM_NEW'
export const EDIT_ITEM_UPDATE = 'utter/editing/EDIT_ITEM_UPDATE'
export const EDIT_ITEM_APPLY = 'utter/editing/EDIT_ITEM_APPLY'
export const EDIT_ITEM_STOP = 'utter/editing/EDIT_ITEM_STOP'
export const EDIT_ITEM_RESET = 'utter/editing/EDIT_ITEM_RESET'
